services:
  frontend:
    container_name: app
    build:
      context: ./build-up-frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

  backend:
    container_name: service
    build:
      context: ./build-up-backend
    environment:
      SPRING_CONFIG_LOCATION: "file:/app/application.properties"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - services_network

  mysql:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "build_up_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3307:3306"
    networks:
      - services_network

networks:
  services_network:
