services:
  frontend:
    container_name: app
    build:
      context: ./build-up-frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

  backend:
    container_name: service
    build:
      context: ./build-up-backend
    ports:
      - "8080:8080"
    restart: always
#    depends_on:
#      - mysql

  mysql:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'build_up_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    ports:
      - "3307:3307"