name: Docker Compose Action

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - dev

jobs:
  build_image_and_test_compose_up:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: actions/checkout@v3
      - name: Build Docker images and compose up
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yaml"
          down-flags: "--rmi local -v"